"""initial migration

Revision ID: 36bdedb25b36
Revises: 
Create Date: 2020-12-14 07:56:39.902708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36bdedb25b36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('students')
    op.drop_table('tbl_keyword')
    op.drop_table('pelicana_crawling')
    op.drop_table('tbl_crawlingdata')
    op.drop_table('tour_crawling')
    op.drop_column('puppies', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('age', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.create_table('tour_crawling',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('term', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('area', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('regdate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_crawlingdata',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('area', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contents', mysql.TEXT(), nullable=True),
    sa.Column('keyword', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('regdate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('pelicana_crawling',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('store', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sido', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('gungu', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('regdate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_keyword',
    sa.Column('keyword', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('keyword'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('students',
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('addr', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pin', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('toys')
    op.drop_table('owners')
    # ### end Alembic commands ###
